FROM almalinux
ADD https://raw.githubusercontent.com/Yaswanth345/Docker-Zero-to-Hero/main/examples/python-web-app/requirements.txt /tmp/
ADD apache-tomcat-9.0.74.tar.gz /tmp/
ADD apache-tomcat-9.0.74.zip /tmp/